package com.cie.nems.monitor.device;

public enum DeviceMonitorColumn {
	monitor_id("monitor_id"),
	monitor_date("monitor_date"),
	customer_id("customer_id"),
	station_id("station_id"),
	device_id("device_id"),
	real_alarms("real_alarms"),
	real_alarms_time("real_alarms_time"),
	last_alarm_time("last_alarm_time"),
	uncheck_alarms("uncheck_alarms"),
	uncheck_alarms_time("uncheck_alarms_time"),
	day_alarms("day_alarms"),
	commu_status("commu_status"),
	commu_status_time("commu_status_time"),
	last_data_time("last_data_time"),
	day_offline_num("day_offline_num"),
	day_offline_dur("day_offline_dur"),
	run_status("run_status"),
	day_run_status("day_run_status"),
	run_status_time("run_status_time"),
	run_start_time("run_start_time"),
	run_end_time("run_end_time"),
	run_times("run_times"),
	day_stop_num("day_stop_num"),
	fault_stop_duration("fault_stop_duration"),
	update_time("update_time"),
	value1("value1"),
	value2("value2"),
	value3("value3"),
	value4("value4"),
	value5("value5"),
	value6("value6"),
	value7("value7"),
	value8("value8"),
	value9("value9"),
	value10("value10"),
	value11("value11"),
	value12("value12"),
	value13("value13"),
	value14("value14"),
	value15("value15"),
	value16("value16"),
	value17("value17"),
	value18("value18"),
	value19("value19"),
	value20("value20"),
	value21("value21"),
	value22("value22"),
	value23("value23"),
	value24("value24"),
	value25("value25"),
	value26("value26"),
	value27("value27"),
	value28("value28"),
	value29("value29"),
	value30("value30"),
	value31("value31"),
	value32("value32"),
	value33("value33"),
	value34("value34"),
	value35("value35"),
	value36("value36"),
	value37("value37"),
	value38("value38"),
	value39("value39"),
	value40("value40"),
	value41("value41"),
	value42("value42"),
	value43("value43"),
	value44("value44"),
	value45("value45"),
	value46("value46"),
	value47("value47"),
	value48("value48"),
	value49("value49"),
	value50("value50");

	private final String name;
	private DeviceMonitorColumn(String name) {
		this.name = name;
	}
	public String getName() {
		return this.name;
	}
}
